In [1]:
student_tuples = [
        ('john', 'A', 15),
        ('jane', 'B', 12),
        ('dave', 'B', 10),
]
sorted(student_tuples, key=lambda x:x[2])

[('dave', 'B', 10), ('jane', 'B', 12), ('john', 'A', 15)]

In [2]:
import random
random.randint(1,101)

55

In [14]:
str(9)>str(0)

True

In [2]:
'0'<'9'

True

In [3]:
1<2<3

True

In [4]:
('a','z')

('a', 'z')

In [5]:
range('a','z')

TypeError: 'str' object cannot be interpreted as an integer

In [6]:
'asdf  dasf adf f     dsfa'.split()

['asdf', 'dasf', 'adf', 'f', 'dsfa']

In [3]:
a = [[] for i in range(5)]

In [4]:
a[1][1] = 3

IndexError: list assignment index out of range

In [1]:
a=[]
a[2]=1

IndexError: list assignment index out of range

In [4]:
{2:1}.keys()

dict_keys([2])

In [1]:
2 in {2:1}

True

In [1]:
a = 1
"{}".format(a)

'1'

In [5]:
from rdkit import Chem
from mordred import Calculator, descriptors
calc = Calculator(descriptors, ignore_3D=False)
mol1 = calc(Chem.MolFromSmiles('O=C(O)c1c(OC(=O)C)cccc1'))
mol2 = calc(Chem.MolFromSmiles('c1(OC(C)=O)ccccc1C(O)=O'))

In [9]:
# print(list(mol1))
# print(list(mol2))
print(list([list(mol1)[i],list(mol2)[i]] for i in range(len(mol1))))

[[9.549067125350073, 9.54906712535007], [9.039192285773227, 9.039192285773227], [1, 1], [0, 0], [15.284972566451408, 15.284972566451394], [2.3067677175277583, 2.306767717527756], [4.613535435055516, 4.613535435055512], [15.284972566451408, 15.284972566451394], [1.175767120496262, 1.175767120496261], [3.450864981353601, 3.4508649813536], [3.2539318909608386, 3.25393189096084], [0.2503024531508337, 0.2503024531508338], [1.4422283421789155, 1.442228342178916], [53.717738796956375, 53.71773879695628], [4.132133753612029, 4.132133753612022], [4.246107542849359, 4.246107542849357], [6, 6], [6, 6], [21, 21], [13, 13], [0, 0], [0, 0], [4, 4], [8, 8], [0, 0], [9, 9], [0, 0], [4, 4], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [234.0, 234.0], [203.0, 203.0], [274.0, 274.0], [250.0, 250.0], [251.0, 251.0], [159.0, 159.0], [98.0, 98.0], [0.0, 0.0], [0.0, 0.0], [68.0, 68.0], [78.0, 78.0], [111.0, 111.0], [114.0, 114.0], [94.0, 94.0], [70.0, 70.0], [48.0, 48.0], [23.0, 23.0], [6.0, 6.0],

In [1]:
a = {}
a['a']=1

In [2]:
print(a)

{'a': 1}


In [4]:
a["dfjkla"[0]]=1

In [5]:
print(a)

{'a': 1, 'd': 1}


In [1]:
5//2

2

In [1]:
l = [[1,1],[1,2],[3,5]]
mat = [[False for i in range(3)] for j in range(3)]

In [2]:
mat

[[False, False, False], [False, False, False], [False, False, False]]

In [3]:
import numpy as np
np_mat = np.full((3,3),False,dtype=bool)

In [4]:
np_mat

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [6]:
np_mat[0][1]

False

In [8]:
np_mat[0,1]

False

In [9]:
l1 = []
l1[0] = 3

IndexError: list assignment index out of range

In [2]:
'a'+('a')

'aa'

In [3]:
'a'*2

'aa'

In [4]:
a,b='',3

In [5]:
a,b

('', 3)

In [3]:
from collections import Counter
cnt = Counter()
cnt.items()

dict_items([])

In [6]:
a = (3==2?3:2)

SyntaxError: invalid syntax (<ipython-input-6-ecddb303993d>, line 1)

In [15]:
a=1
b=2
a = b+a if a==b else

SyntaxError: invalid syntax (<ipython-input-15-f38f31a307ee>, line 3)

In [16]:
if a==b: pass

In [18]:
a=0
a += i for i in range(10) if i%2==0

SyntaxError: invalid syntax (<ipython-input-18-de671154572c>, line 2)

In [1]:
10**2

100

In [4]:
x = 'b'
if 'a'<x<'c': print('x')

x


In [5]:
range('a','z')

TypeError: 'str' object cannot be interpreted as an integer

In [10]:
from copy import copy, deepcopy
s = "ssfdasfa"
a = copy(s[0])
s[1]='x'
s

TypeError: 'str' object does not support item assignment

In [12]:
l = list(s)
s = str(l)
s

"['s', 's', 'f', 'd', 'a', 's', 'f', 'a']"

In [14]:
sum('a','b')

TypeError: sum() can't sum strings [use ''.join(seq) instead]

In [1]:
[1]*3

[1, 1, 1]

In [4]:
"123+456".split('+')

TypeError: 'str' object cannot be interpreted as an integer

In [2]:
int('1')

1

In [5]:
"adsf+".split('+')

AttributeError: 'list' object has no attribute 'split'

In [2]:
a=1
a, b = 2,a+1

In [3]:
b

2

In [3]:
s="**|**|***|"
s[2]=='|'

True

In [4]:
s = 'jdfiasieofjksaf'
s = s.split('.nsp')[0]
s

'jdfiasieofjksaf'

In [7]:
target = 'a'
l = [1,2,3]
print([target]+l)

['a', 1, 2, 3]


In [3]:
from numpy import *
array([1,2,3]) * array([4,5,6])

array([ 4, 10, 18])

In [7]:
import numpy as np
n = 1
a = np.zeros((n,n), dtype=np.int)
a[0,0]

0

In [6]:
3 in range(3,2)

False

In [20]:
class Solution:
    def findLongestChain(self, pairs) -> int:
        # 一次扫描，对所有数排序，确定矩阵大小
        # 二维矩阵：行数和列数是小数和大数，数值是两者之间的路径长度
        # 进行第二次扫描，每次对三维矩阵进行更新
        # 遍历二维矩阵，找出最大值
        import numpy as np

        numbers = []
        for i in pairs:
            for j in i:
                if j not in numbers:
                    numbers.append(j)
        n = len(numbers)
        numbers = sorted(numbers)
        path = np.zeros((n,n), dtype=np.int)
        for pair in pairs:
            i, j = numbers.index(pair[0]), numbers.index(pair[1])
            if path[i,j] == 0:
                path[i,j] = 1
                for _ in range(j+1, n):
                    for __ in range(_+1, n):
                        if path[_, __]!=0:
                            path[i, __] == max(path[i, __], path[_+1, n]+1)
                for _ in range(0, i):
                    for __ in range(_, i):
                        if path[_, __] != 0:
                            path[_, j] += 1
        return max(map(max, path))

ans = Solution()
print(ans.findLongestChain([[1,2], [3,4], [2,3]]))
print(ans.findLongestChain([[3,4], [2,3]]))
print(ans.findLongestChain([[1,2], [3,4]]))
print(ans.findLongestChain([[1,2], [3,4], [3,5], [4,6], [2,5], [2,4], [1,3], [1,2], [3,6]]))

2
1
2
5


In [24]:
dict = {}
dict[0] = True
1 in dict

False

In [27]:
mat = [[]]
len(mat[0])

0

In [29]:
not 0 and 1

1

In [31]:
from enum import Enum
class numof1(Enum):
    zero:0
    one:1
    over1:2

In [4]:
class Solution:
    def uniqueLetterString(self, s: str) -> int:
        
        if len(s)==1: return 1
        
        def order(c: str) -> int:
            return ord(c)-65

        # from enum import Enum
        # class Num(Enum):
        #     ZERO = 0
        #     ONE = 1
        #     TWO = 2

        ans = 0
        import numpy as np
        n = len(s)
        for i in range(n):
            if i==0:
                ans += 1
                continue
            else:
                # char_exist = np.zeros(26, dtype=Num)
                char_exist = np.zeros(26, dtype=np.int8)
                add = 0
                for j in range(i,-1,-1):
                    if char_exist[order(s[j])] == 0:
                        char_exist[order(s[j])] = 1
                        add += 1
                        ans += add
                    elif char_exist[order(s[j])] == 1:
                        char_exist[order(s[j])] = 2
                        add -= 1
                        ans += add
                    else:
                        ans += add
        return ans
    
s = Solution()
s.uniqueLetterString('ABC')



            


10

In [5]:
a = 1
a++
a

<class 'SyntaxError'>: invalid syntax (C:/Users/ADMINI~1/AppData/Local/Temp/xpython_14944/898971460.py, line 2)

In [16]:
a = []
a.extend([1,1])
a

[1, 1]

In [17]:
1+1

2

In [3]:
import numpy as np
np.linspace(1,5,5, dtype=int)

array([1, 2, 3, 4, 5])

In [17]:
a = []
a.extend(np.linspace(1,5,5, dtype=int))
type(int(a[0]))

int